# -*- coding: utf-8 -*-
"""Module 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZX1PUxFB1nBGIqNRazNoKtoEnmyyS1a5

1:
"""

list_of_tuples = [('Sachin Tendulkar', 34357), ('Ricky Ponting', 27483), ('Jack Kallis', 25534), ('Virat Kohli', 24936)]

sorted_list = sorted(list_of_tuples, key=lambda x: x[1])

sorted_list

"""2:"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
squared_numbers = list(map(lambda x: x**2, numbers))
squared_numbers

"""3:"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
string_tuple = tuple(map(lambda x: str(x), numbers))
string_tuple

"""4:"""

from functools import reduce
import operator

numbers = list(range(1, 26))

product = reduce(operator.mul, numbers)

product

"""5:"""

numbers = [2, 3, 6, 9, 27, 60, 90, 120, 55, 46]

def check(num):
  if num % 2 == 0 and num % 3 == 0:
    return True
  return False

filtered_numbers = list(filter(check, numbers))

filtered_numbers

"""6:"""

strings = ['python', 'php', 'aba', 'radar', 'level']

palindromes = list(filter(lambda x: x == x[::-1], strings))

palindromes